# This is second workflow to help you get started with Actions

name: Deploy Node.js Beta Project
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: NodeBeta
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: NodeBeta
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: NodeBeta
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
        