# This is second workflow to help you get started with Actions

name: Test Node.js Project
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: Node
    steps:
      - name: Get Code
        uses: actions/checkout
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

